name = "Mojolicious-Plugin-Template-Mustache"
badges = ["metacpan", "travis"]
authority="cpan:CYNOVG"
module_maker="ModuleBuildTiny"

license="lgpl_3_0"
[release]
pause_config = "/home/cynovg/.pause"

